[package]
name = "ts"
version = "0.1.5"
edition = "2021"

[features]
default = []
with_dynamic = ["bevy/dynamic_linking"]

[dependencies]
bevy = { version = "0.14", features = [] }
bevy_egui = "0.28"
rand = "0.8"
rayon = "1.10"
ndarray = "0.16"
wgpu = "0.20"
bytemuck = "1.18"
log = "0.4"
env_logger = "0.11"
num_cpus = "1.16.0"
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
