use crate::resources::Language;

pub struct UiText {
    pub points_slider: &'static str,
    pub generate_points: &'static str,
    pub start: &'static str,
    pub stop: &'static str,
    pub positions_count: &'static str,
    pub elapsed_time: &'static str,
    pub estimated_time: &'static str,
    pub estimated_time_short: &'static str, // Versão compacta
    pub over_a_year: &'static str,
    pub over_a_century: &'static str,
    pub over_a_millennium: &'static str, 
    pub over_10_millennia: &'static str,
    pub over_1000_millennia: &'static str,
    pub months: &'static str,
    pub days: &'static str,
    pub hours: &'static str,
    pub minutes: &'static str,
    pub seconds: &'static str,
    pub iterations: &'static str,
    pub best_distance: &'static str,
    pub algorithm_parameters: &'static str,
    pub ant_count: &'static str,
    pub each_ant_starts: &'static str,
    pub ants_distributed: &'static str,
    pub alpha: &'static str,
    pub beta: &'static str,
    pub rho: &'static str,
    pub q_factor: &'static str,
    pub reset_parameters: &'static str,
    pub language: &'static str,
    pub start_tooltip: &'static str,
}

pub fn get_text(language: Language) -> UiText {
    match language {
        Language::English => UiText {
            points_slider: "Points",
            generate_points: "Generate Points",
            start: "Start",
            stop: "Stop",
            positions_count: "Positions count: {}",
            elapsed_time: "Elapsed: {:02}:{:02}.{:03}",
            estimated_time: "Estimated time for standard algorithm: {}",
            estimated_time_short: "Est. brute-force time: {}", // Versão compacta
            over_a_year: "over a year (impractical)",
            over_a_century: "over a century (impossible)",
            over_a_millennium: "over a millennium (absurd)",
            over_10_millennia: "over 10 millennia (cosmic)",
            over_1000_millennia: "over 10³ millennia (universal)",
            months: "{:.1} months",
            days: "{:.1} days",
            hours: "{:.1} hours",
            minutes: "{:.1} minutes",
            seconds: "{}.{:03} seconds",
            iterations: "Iterations: {}",
            best_distance: "Best distance: {:.2}",
            algorithm_parameters: "Algorithm Parameters",
            ant_count: "Ant Count",
            each_ant_starts: "Each ant starts at a different point (total: {})",
            ants_distributed: "Ants distributed randomly among {} points",
            alpha: "Alpha (pheromone importance)",
            beta: "Beta (distance importance)",
            rho: "Rho (evaporation rate)",
            q_factor: "Q (pheromone deposit)",
            reset_parameters: "Reset Parameters",
            language: "Language",
            start_tooltip: "Press to start/restart the algorithm with current parameters on the same points",
        },
        Language::Portuguese => UiText {
            points_slider: "Pontos",
            generate_points: "Gerar Pontos",
            start: "Iniciar",
            stop: "Parar",
            positions_count: "Total de posições: {}",
            elapsed_time: "Tempo decorrido: {:02}:{:02}.{:03}",
            estimated_time: "Tempo estimado para algoritmo padrão: {}",
            estimated_time_short: "Est. força bruta: {}", // Versão compacta
            over_a_year: "mais de um ano (impraticável)",
            over_a_century: "mais de um século (impossível)",
            over_a_millennium: "mais de um milênio (absurdo)",
            over_10_millennia: "mais de 10 milênios (cósmico)",
            over_1000_millennia: "mais de 10³ milênios (universal)",
            months: "{:.1} meses",
            days: "{:.1} dias",
            hours: "{:.1} horas",
            minutes: "{:.1} minutos",
            seconds: "{}.{:03} segundos",
            iterations: "Iterações: {}",
            best_distance: "Melhor distância: {:.2}",
            algorithm_parameters: "Parâmetros do Algoritmo",
            ant_count: "Quantidade de Formigas",
            each_ant_starts: "Cada formiga inicia em um ponto distinto (total: {})",
            ants_distributed: "Formigas distribuídas aleatoriamente entre {} pontos",
            alpha: "Alpha (importância do feromônio)",
            beta: "Beta (importância da distância)",
            rho: "Rho (taxa de evaporação)",
            q_factor: "Q (depósito de feromônio)",
            reset_parameters: "Redefinir Parâmetros",
            language: "Idioma",
            start_tooltip: "Pressione para iniciar/reiniciar o algoritmo com os parâmetros atuais nos mesmos pontos",
        },
    }
}
